#!/usr/bin/env bash

DOWNLOADS="$HOME/Downloads"

organize_file() {
	filename="$1"

	case "$filename" in
		*.txt)
		mkdir -p "$DOWNLOADS/text"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/text/"
		;;
		*.pdf)
		mkdir -p "$DOWNLOADS/pdfs"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/pdfs/"
		;;
		*.doc|*.docx|*.odt)
		mkdir -p "$DOWNLOADS/docs"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/docs/"
		;;
		*.jpg|*.jpeg|*.png|*.gif)
		mkdir -p "$DOWNLOADS/images"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/images/"
		;;
		*.mp4|*.mkv|*.avi)
		mkdir -p "$DOWNLOADS/video"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/videos/"
		;;
		*.mp3|*.wav)
		mkdir -p "$DOWNLOADS/audio"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/audio/"
		;;
		*.zip|*.tar|*.gz)
		mkdir -p "$DOWNLOADS/archives"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/archives/"
		;;
		*)
		mkdir -p "$DOWNLOADS/other"
		mv "$DOWNLOADS/$filename" "$DOWNLOADS/other/"
		;;
	esac
}

mkdir -p "$DOWNLOADS/text"
mkdir -p "$DOWNLOADS/pdfs"
mkdir -p "$DOWNLOADS/docs"
mkdir -p "$DOWNLOADS/images"
mkdir -p "$DOWNLOADS/videos"
mkdir -p "$DOWNLOADS/audio"
mkdir -p "$DOWNLOADS/archives"
mkdir -p "$DOWNLOADS/other"

# Organize files that already exist in Downloads
for file in "$DOWNLOADS"/*
do
	if [ -f "$file" ]; then
	organize_file "$(basename "$file")"
	
	fi
done

# Monitor Downloads for new or moved files
inotifywait -m -e close_write -e moved_to "$DOWNLOADS" | while read -r directory event filename

do	
	if [ -f "$DOWNLOADS/$filename" ]; then
		organize_file "$filename"

	fi
done


